import type {
  Gen1BagState,
  Gen1BattleState,
  Gen1Pokemon,
  Gen1ProgressState,
  Gen1SafariState,
} from "@emulnk/sdk/transforms/gen1";
import type { Gen1GameVersion } from "./encounter-data.generated.js";

export const emptyBattle: Gen1BattleState = {
  active: false,
  isTrainer: false,
  isSafari: false,
  isOldMan: false,
  player: null,
  enemy: null,
  playerStatMods: { atk: 0, def: 0, speed: 0, special: 0, accuracy: 0, evasion: 0 },
  enemyStatMods: { atk: 0, def: 0, speed: 0, special: 0, accuracy: 0, evasion: 0 },
  playerStatus: {
    storingEnergy: false,
    thrashing: false,
    attackingMultipleTimes: false,
    flinched: false,
    charging: false,
    trapping: false,
    invulnerable: false,
    confused: false,
    usingXAccuracy: false,
    protectedByMist: false,
    gettingPumped: false,
    hasSubstitute: false,
    needsRecharge: false,
    usingRage: false,
    seeded: false,
    badlyPoisoned: false,
    lightScreen: false,
    reflect: false,
    transformed: false,
    numAttacksLeft: 0,
    confusedTurns: 0,
    toxicCounter: 0,
    disabledMoveSlot: 0,
    disabledTurns: 0,
    substituteHp: 0,
    selectedMoveId: 0,
    usedMoveId: 0,
    raw: [0, 0, 0],
  },
  enemyStatus: {
    storingEnergy: false,
    thrashing: false,
    attackingMultipleTimes: false,
    flinched: false,
    charging: false,
    trapping: false,
    invulnerable: false,
    confused: false,
    usingXAccuracy: false,
    protectedByMist: false,
    gettingPumped: false,
    hasSubstitute: false,
    needsRecharge: false,
    usingRage: false,
    seeded: false,
    badlyPoisoned: false,
    lightScreen: false,
    reflect: false,
    transformed: false,
    numAttacksLeft: 0,
    confusedTurns: 0,
    toxicCounter: 0,
    disabledMoveSlot: 0,
    disabledTurns: 0,
    substituteHp: 0,
    selectedMoveId: 0,
    usedMoveId: 0,
    raw: [0, 0, 0],
  },
  catch: null,
};

export const emptyProgress: Gen1ProgressState = {
  owned: [],
  seen: [],
  ownedCount: 0,
  seenCount: 0,
  badges: [false, false, false, false, false, false, false, false],
  badgeCount: 0,
  currentMap: -1,
  mapName: "Unknown",
};

export const emptySafari: Gen1SafariState = {
  escapeFactor: 0,
  baitFactor: 0,
  steps: 0,
  balls: 0,
  active: false,
};

export const emptyBag: Gen1BagState = {
  count: 0,
  declaredCount: 0,
  capacity: 20,
  items: [],
  balls: [],
};

export const appState = $state({
  isConnected: false,
  settings: {} as Record<string, string>,
  party: [null, null, null, null, null, null] as Array<Gen1Pokemon | null>,
  battle: emptyBattle,
  bag: emptyBag,
  progress: emptyProgress,
  safari: emptySafari,
  gameVersion: "red" as Gen1GameVersion,
});
